apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-microservice-app
  template:
    metadata:
      labels:
        app: my-microservice-app
    spec:
      containers:
      - name: viralnationmicroservice
        image: myacrrepo312.azurecr.io/sayeeshruthii/viralnationmicroservice:#{Build.BuildId}#
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: my-microservice-app-svc
spec:
  selector:
    app: my-microservice-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer