apiVersion: apps/v1
kind: Deployment
metadata:
  name: viralnation-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: viralnation-microservice-app
  template:
    metadata:
      labels:
        app: viralnation-microservice-app
    spec:
      containers:
      - name: viralnationmicroservice
        image: sayeecontainerregistry.azurecr.io/sayeeshruthii/viralnationmicroservice:16
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: viralnation-microservice-app-svc
spec:
  selector:
    app: viralnation-microservice-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer